# Generated by Django 3.2.2 on 2021-05-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Totic',
            new_name='Topic',
        ),
    ]
