# Generated by Django 3.2.2 on 2021-05-07 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='hours_topic',
            field=models.CharField(choices=[(1, 'One'), (2, 'Two')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
    ]
