# Generated by Django 3.2.2 on 2021-05-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_topic_hours_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='hours_topic',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two')], default=0),
        ),
    ]
