# Generated by Django 3.2.2 on 2021-05-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_alter_topic_hours_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='Upload_Image_For_Topic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
