# Generated by Django 3.2.2 on 2021-05-07 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_person_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('d', 'Draf'), ('p', 'Published')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
