# Generated by Django 3.2.2 on 2021-05-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_person_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='date',
            new_name='date_added',
        ),
    ]
